"""Initial migration: create isolated omni users and memories

Revision ID: b82751a97948
Revises:
Create Date: 2026-06-04 12:29:51.865312

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# import pgvector
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = "b82751a97948"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("platform_user_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="omni",
    )
    op.create_table(
        "agent_memories",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        # sa.Column(
        #     "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False
        # ),
        sa.Column("embedding", VECTOR(dim=384), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["omni.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="omni",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_memories", schema="omni")
    op.drop_table("users", schema="omni")
    # ### end Alembic commands ###
